dataset:
  data_path: data/nas-101/
  dev_ratio: 0.2
  has_node_feat: false
  is_overwrite_precompute: true
  is_sample_subgraph: true
  is_save_split: true
  loader_name: GRANData_Node_Level
  max_num_samples: 100
  max_test_accuracy: 40
  min_test_accuracy: 0
  name: nas
  node_order: none
  num_fwd_pass: 2
  num_subgraph_batch: 2
  train_ratio: 0.8
device: cuda:6
exp_dir: exp/SEARCH
exp_name: '72108'
free_cache: false
gpus:
- 6
model:
  block_size: 1
  dimension_reduce: true
  display_detailed_model: false
  edge_weight: 1.0
  embedding_dim: 256
  has_attention: true
  hidden_dim: 256
  is_sym: false
  max_num_nodes: 6
  name: GRANMixtureBernoulli_Evaluation
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 64
  sample_stride: 1
run_id: '72108'
runner: GranRunner_Search
save_dir: exp/SEARCH/72108
seed: 67812345
test:
  batch_size: 20
  better_vis: true
  generated_graph_data_dir: generated_data
  is_single_plot: false
  is_test_ER: false
  is_vis: true
  num_test_gen: 20
  num_vis: 10
  num_workers: 0
  test_model_dir: exp/SEARCH/72108
  test_model_name: model_snapshot_search_6.pth
  vis_num_row: 1
train:
  batch_size: 20
  display_iter: 10
  is_resume: false
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 100000000
  max_epoch: 50
  momentum: 0.9
  num_workers: 0
  optimizer: Adam
  resume_dir: null
  resume_epoch: 100
  resume_model: null
  shuffle: true
  snapshot_epoch: 50
  valid_epoch: 50
  wd: 0.0
use_gpu: true
use_horovod: false
